### ISSUE TITLE
Boost not working with FetchContent_MakeAvailable(SetupHunter)

### ISSUE THREAD

**Issue by drywolf** [cpp-pm/hunter#93] opened 2019-12-08 04:03 UTC
I have been using `FetchContent_MakeAvailable(SetupHunter)` with multiple different packages successfully already, but now I tried it with Boost and it failed with the following errors:
```
CMake Error at C:/.hunter/_Base/b67e11d/083dd95/9877faf/Install/lib/cmake/Boost/BoostConfig.cmake:4 (include):
  include could not find load file:

    hunter_check_toolchain_definition
Call Stack (most recent call first):
  CMakeLists.txt:15 (find_package)


CMake Error at C:/.hunter/_Base/b67e11d/083dd95/9877faf/Install/lib/cmake/Boost/BoostConfig.cmake:7 (include):
  include could not find load file:

    hunter_internal_error
Call Stack (most recent call first):
  CMakeLists.txt:15 (find_package)


CMake Error at C:/.hunter/_Base/b67e11d/083dd95/9877faf/Install/lib/cmake/Boost/BoostConfig.cmake:8 (include):
  include could not find load file:

    hunter_status_debug
Call Stack (most recent call first):
  CMakeLists.txt:15 (find_package)



[hunter ** INTERNAL **] Unexpected empty string
[hunter ** INTERNAL **] [Directory:C:/.hunter/_Base/b67e11d/083dd95/9877faf/Install/lib/cmake/Boost]

------------------------------ ERROR -----------------------------
    /error.internal.html
------------------------------------------------------------------

CMake Error at C:/.hunter/_Base/Download/Hunter/0.23.234/b67e11d/Unpacked/cmake/modules/hunter_error_page.cmake:12 (message):
Call Stack (most recent call first):
  C:/.hunter/_Base/Download/Hunter/0.23.234/b67e11d/Unpacked/cmake/modules/hunter_internal_error.cmake:13 (hunter_error_page)
  C:/.hunter/_Base/Download/Hunter/0.23.234/b67e11d/Unpacked/cmake/modules/hunter_assert_not_empty_string.cmake:9 (hunter_internal_error)
  C:/.hunter/_Base/Download/Hunter/0.23.234/b67e11d/Unpacked/cmake/modules/hunter_check_toolchain_definition.cmake:46 (hunter_assert_not_empty_string)
  C:/.hunter/_Base/b67e11d/083dd95/9877faf/Install/lib/cmake/Boost/BoostConfig.cmake:43 (hunter_check_toolchain_definition)
  CMakeLists.txt:15 (find_package)
```
The CMakeLists.txt looks like follows:
```cmake
cmake_minimum_required(VERSION 3.2)

set(HUNTER_Boost_COMPONENTS chrono date_time)
set(HUNTER_PACKAGES Boost)
set(HUNTER_Boost_VERSION 1.71.0-p0)

# option(HUNTER_NO_TOOLCHAIN_ID_RECALCULATION "" ON)

include(FetchContent)
FetchContent_Declare(SetupHunter GIT_REPOSITORY https://github.com/cpp-pm/gate)
FetchContent_MakeAvailable(SetupHunter)

project(use-pkg-components)

find_package(Boost CONFIG REQUIRED chrono date_time)

add_executable(use-pkg-components main.cpp)

target_link_libraries(use-pkg-components PRIVATE
    Boost::chrono
    Boost::date_time
)
```

Interestingly the same basic setup works fine when I manually download & set up HunterGate.cmake:
```cmake
cmake_minimum_required(VERSION 3.2)

set(HUNTER_Boost_COMPONENTS chrono date_time)
set(HUNTER_PACKAGES Boost)
set(HUNTER_Boost_VERSION 1.71.0-p0)

# option(HUNTER_NO_TOOLCHAIN_ID_RECALCULATION "" ON)

include("cmake/HunterGate.cmake")
HunterGate(
    URL "https://github.com/cpp-pm/hunter/archive/v0.23.234.tar.gz"
    SHA1 "b67e11d7e9ee503e9f6e1b45eb1ef7bf2fb31279"
)

project(use-pkg-components)

hunter_add_package(Boost COMPONENTS chrono date_time)
find_package(Boost CONFIG REQUIRED chrono date_time)

add_executable(use-pkg-components main.cpp)

target_link_libraries(use-pkg-components PRIVATE
    Boost::chrono
    Boost::date_time
)
```

Any ideas what could be the issue ?
Thanks

**Comment by drywolf** [comment] 2019-12-08 22:38
I have debugged this problem a little bit and I at least found an (ugly but functioning) workaround:
https://gist.github.com/drywolf/db3fc3ec2cd28bcdfa14c82aaf043949/revisions?diff=split

1) It required to manually add the Hunter cmake module paths, so that the include(...) calls start working:
```
string(SUBSTRING "${HUNTER_SHA1}" 0 7 HUNTER_ID)
# string(SUBSTRING "${HUNTER_CONFIG_SHA1}" 0 7 HUNTER_CONFIG_ID)
# string(SUBSTRING "${HUNTER_TOOLCHAIN_SHA1}" 0 7 HUNTER_TOOLCHAIN_ID)

set(HUNTER_CMAKE_DIR "${HUNTER_CACHED_ROOT}/_Base/Download/Hunter/${HUNTER_VERSION}/${HUNTER_ID}/Unpacked/cmake")
list(APPEND CMAKE_MODULE_PATH "${HUNTER_CMAKE_DIR}/modules")
list(APPEND CMAKE_MODULE_PATH "${HUNTER_CMAKE_DIR}/find")
```

2) before the call to find_package(...) I need to call `hunter_finalize()` otherwise the internal hunter variables that are required for the Boost config / find scripts are not set.
(e.g. `${HUNTER_TOOLCHAIN_ID_PATH}` is empty and this causes an error in `cmake\modules\hunter_check_toolchain_definition.cmake:46 > hunter_assert_not_empty_string("${HUNTER_TOOLCHAIN_ID_PATH}")`)

This is just a workaround though, I still can't tell why this is even necessary.
How bad this workaround is becomes clear in the cmake output, as I can clearly see that hunter_finalize() is now being executed twice.
```
[hunter] Calculating Toolchain-SHA1
[hunter] Calculating Config-SHA1
[hunter] HUNTER_ROOT: C:/.hunter
[hunter] [ Hunter-ID: b67e11d | Toolchain-ID: 083dd95 | Config-ID: 9877faf ]
[hunter] BOOST_ROOT: C:/.hunter/_Base/b67e11d/083dd95/9877faf/Install (ver.: 1.71.0-p0)
[hunter] BOOST_ROOT: C:/.hunter/_Base/b67e11d/083dd95/9877faf/Install (ver.: 1.71.0-p0)
[hunter] BOOST_ROOT: C:/.hunter/_Base/b67e11d/083dd95/9877faf/Install (ver.: 1.71.0-p0)
[hunter] HUNTER_ROOT: C:/.hunter
[hunter] [ Hunter-ID: b67e11d | Toolchain-ID: 083dd95 | Config-ID: 9877faf ]
Boost version: 1.71.0
Found the following Boost libraries:
  chrono
  date_time
Configuring done
Generating done
```
I hope this can help someone more knowledgeable about the hunter internals to figure out what is causing this bug.

**Comment by drywolf** [comment] 2019-12-08 22:42
PS: at first I had moved the find_package() call right before the project() call, this also allowed the CMake configure phase to finish without any errors.
But in the generated Visual Studio project the boost library directories were not properly set, and then I got an error that visual studio could not find the boost libraries for linking.

Maybe this detail can also be important to consider when fixing the bug, i.e. is there a hard requirement that find_package() must be called before or after project() ?

**Comment by rbsheth** [comment] 2019-12-09 22:10
I'm not too sure about the new FetchContent ability - @cristianadam can you help?

I think `find_package()` is normally called after `project()`.

**Comment by cristianadam** [comment] 2019-12-10 12:39
I've tried your snippet and got a different error with MinGW 8.1.0

```
[6/8 0.0/sec]Performing build step for 'Boost-chrono'
FAILED: Boost-chrono-prefix/src/Boost-chrono-stamp/Boost-chrono-build
cmd.exe /C "cd /D C:\.hunter\_Base\d8992c8\a76317a\d6df02a\Build\Boost\__chrono\Source && b2 target-os=windows -a link=static threading=multi variant=debug,release --layout=tagged toolset=gcc --user-config=C:/.hunter/_Base/d8992c8/a76317a/d6df02a/Build/Boost/__chrono/Build/boost.user.jam --with-chrono -j 8 --ignore-site-config && C:\Tools\cmake\bin\cmake.exe -E touch C:/.hunter/_Base/d8992c8/a76317a/d6df02a/Build/Boost/__chrono/Build/Boost-chrono-prefix/src/Boost-chrono-stamp/Boost-chrono-build"
error: at project-config.jam:6
error: duplicate initialization of gcc with the following parameters:
error: version = 8.1.0
error: previous initialization at C:\.hunter\_Base\d8992c8\a76317a\d6df02a\Build\Boost\__chrono\Build\boost.user.jam:6

ninja: build stopped: subcommand failed.

[hunter ** FATAL ERROR **] Build step failed (dir: C:/.hunter/_Base/d8992c8/a76317a/d6df02a/Build/Boost/__chrono
[hunter ** FATAL ERROR **] [Directory:C:/.hunter/_Base/Download/Hunter/0.23.235/d8992c8/Unpacked/cmake/projects/Boost/chrono]

------------------------------ ERROR -----------------------------
    https://cpp-pm-hunter.readthedocs.io/en/latest/reference/errors/error.external.build.failed.html
------------------------------------------------------------------

CMake Error at C:/.hunter/_Base/Download/Hunter/0.23.235/d8992c8/Unpacked/cmake/modules/hunter_error_page.cmake:12 (message):
Call Stack (most recent call first):
  C:/.hunter/_Base/Download/Hunter/0.23.235/d8992c8/Unpacked/cmake/modules/hunter_fatal_error.cmake:20 (hunter_error_page)
  C:/.hunter/_Base/Download/Hunter/0.23.235/d8992c8/Unpacked/cmake/modules/hunter_download.cmake:617 (hunter_fatal_error)
  C:/.hunter/_Base/Download/Hunter/0.23.235/d8992c8/Unpacked/cmake/projects/Boost/chrono/hunter.cmake:16 (hunter_download)
  C:/.hunter/_Base/Download/Hunter/0.23.235/d8992c8/Unpacked/cmake/modules/hunter_add_package.cmake:62 (include)
  build/_deps/setuphunter-src/CMakeLists.txt:142 (hunter_add_package)


-- Configuring incomplete, errors occurred!
```

The only difference between manual including the `HunterGate` and uising `FetchContent` would be the latter using `add_subdirectory`. 

I don't know if this is problem with `boost` or with packages that have `COMPONENTS`.

**Comment by Mike-Devel** [comment] 2019-12-12 17:03
> The only difference between manual including the HunterGate and uising FetchContent would be the latter using add_subdirectory.

I don't know anything about hunter and how hunter integrates boost, but I can provide some background info, that may help:

Boost as a whole doesn't support to be build with cmake. Some individual boost libraries have cmake files in their root which is mostly used for development of that particular library and may or may not support `add_subdirectory`.  I and a few others have been (very) slowly adding minimal cmake files to various boost libs (including/especially the header only ones) which work with `add_subdirectory` and will produce `Boost::<libname>` targets. However, those are still the minority and they require that you also add all their dependencies via `add_subdirectory` (or you put a file like this into the boost root dir that does it for you: https://github.com/Mike-Devel/BoostMinCMake_Support/blob/master/root_cmake_file/CMakeLists.txt)

That aside, if you compile and install recent versions of boost with b2, that will produce a cmake config file that can be used by `find_package`. At the same time cmake itself has a FindBoost script which uses its own logic to provide the boost targets (I think in recent versions it first looks for the config file produced by b2).

**Comment by CarloWood** [comment] 2019-12-31 02:59
I ran into the same issue @drywolf ... Started happening when I switched from 'manual' to the FetchContent_MakeAvailable too. Unfortunately I'm not getting much response on https://gitter.im/ruslo/hunter. Are you interested to work together to figure out how to use hunter (and fix it)?

**Comment by CarloWood** [comment] 2019-12-31 03:02
The exact error that I am currently getting is:
```
-- *** *** *** CMAKE_MODULE_PATH = "/home/carlo/projects/aicxx/ai-statefultask-testsuite/ai-statefultask-testsuite/cwm4/cmake"
CMake Error at cwm4/hunter/_Base/xxxxxxx/b5a07b2/a8d2191/Install/lib/cmake/Boost/BoostConfig.cmake:6 (include):
  include could not find load file:

    hunter_check_toolchain_definition
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindBoost.cmake:443 (find_package)
  cwds/CMakeLists.txt:35 (find_package)
```

**Comment by CarloWood** [comment] 2019-12-31 03:04
The missing include is here:
    ./cwm4/hunter/cmake/modules/hunter_check_toolchain_definition.cmake

**Comment by CarloWood** [comment] 2019-12-31 03:11
Switching back to the 'manual' method, I get the addition (and changed) output:

```
-- [hunter] Calculating Toolchain-SHA1
-- [hunter] Calculating Config-SHA1
-- [hunter] HUNTER_ROOT: /opt/hunter
-- [hunter] [ Hunter-ID: ca19f37 | Toolchain-ID: b5a07b2 | Config-ID: a8d2191 ]
-- [hunter] BOOST_ROOT: /opt/hunter/_Base/ca19f37/b5a07b2/a8d2191/Install (ver.: 1.71.0-p0)
-- *1* *** *** CMAKE_MODULE_PATH = "/opt/hunter/_Base/Download/Hunter/0.23.240/ca19f37/Unpacked/cmake/modules;/opt/hunter/_Base/Download/Hunter/0.23.240/ca19f37/Unpacked/cmake/find;/home/carlo/projects/aicxx/ai-statefultask-testsuite/ai-statefultask-testsuite/cwm4/cmake"
Boost  found.
```

**Comment by CarloWood** [comment] 2019-12-31 03:21
It turns out that `CMAKE_MODULE_PATH` is set during the call to `HunterGate(URL "https://github.com/cpp-pm/hunter/archive/v0.23.240.tar.gz" SHA1 "ca19f3769e6c80cfdd19d8b12ba5102c27b074e0")`.

Here is what I'm doing for the non-manual case:

```
# FetchContent_MakeAvailable is available since CMake version 3.14
cmake_minimum_required(VERSION 3.14)

# Use git submodule for Hunter.
set(HUNTER_ROOT "${CMAKE_CURRENT_SOURCE_DIR}/cwm4/hunter")

# Setting up Boost as an external package                                                                                                                              
set(HUNTER_Boost_COMPONENTS filesystem iostreams program_options system)
set(HUNTER_PACKAGES Boost farmhash)

include(FetchContent)
FetchContent_Declare(SetupHunter GIT_REPOSITORY https://github.com/cpp-pm/gate)
FetchContent_MakeAvailable(SetupHunter)
```

**Comment by CarloWood** [comment] 2019-12-31 04:59
As `HunterGate` seems to be the only place where this `_master_location` is included, I tried to add `HunterGate()` (no arguments!) after the `FetchContent_MakeAvailable`. This works.

Thinking it was strange that it didn't complain about being called with no arguments, I tracked this further and found that `HunterGate` is called *before* this by `FetchContent_MakeAvailable` from a generated file `${CMAKE_CURRENT_BINARY_DIR}/HunterSetup.cmake` with the following contents:

```
include("/home/carlo/projects/aicxx/ai-statefultask-testsuite/ai-statefultask-testsuite-objdir/_deps/setuphunter-src/cmake/HunterGate.cmake")
HunterGate(
    URL file:///home/carlo/projects/aicxx/ai-statefultask-testsuite/ai-statefultask-testsuite-objdir/hunter-v0.23.240.tar.gz
    SHA1 xxxxxxxxxx
    FILEPATH;/home/carlo/projects/aicxx/ai-statefultask-testsuite/ai-statefultask-testsuite-objdir/HunterConfig.cmake
   )
```

This then causes the `GLOBAL PROPERTY HUNTER_GATE_DONE` to be set, stopping any subsequent calls to `HunterGate` to do nothing, that is.. they use variables that are not set, because the first call to `HunterGate` wasn't done from the main project but instead from a side-project "setuphunter-src".

The problem is thus with the propagation of all needed info from this initial call to `HunterGate` from the `SetupHunter` 'project' to the real project.

**Comment by CarloWood** [comment] 2019-12-31 10:05
In the end I opted for repeating the call to `HunterGate` (with 'fake' URL and SHA1 which are ignored anyway):

```
# FetchContent_MakeAvailable is available since CMake version 3.14.
cmake_minimum_required( VERSION 3.14 )

# Use local git submodule for Hunter.
set( HUNTER_ROOT "${CMAKE_CURRENT_SOURCE_DIR}/cwm4/hunter" ) 

# Setting up external packages.
set( HUNTER_Boost_COMPONENTS filesystem iostreams program_options system )
set( HUNTER_PACKAGES Boost farmhash )

# Initialize Hunter and build external pacakges.
include( FetchContent )
# Use local git submodule in the source tree.
FetchContent_Declare( SetupHunter SOURCE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/cwm4/hunter/gate" )
FetchContent_MakeAvailable( SetupHunter )

# Refresh CMAKE_MODULE_PATH (this call isn't using the URL or SHA1, what is really being
# used can be found in the generated ${CMAKE_CURRENT_BINARY_DIR}/HunterGate.cmake.
HunterGate(
    URL "https://github.com/cpp-pm/hunter/archive/v0.23.240.tar.gz"
    SHA1 "ca19f3769e6c80cfdd19d8b12ba5102c27b074e0"
)
```

*However* - although this uses, as intended, my git clone (fork) at `HUNTER_ROOT`, it also downloads and compiles all third-party stuff in that `${HUNTER_ROOT}/_Base` which is unacceptable. `_Base` is catenated to the hunter_root, or HUNTER_ROOT or HUNTER_CACHED_ROOT etc all over the place, so cannot be separated it seems.

Because I didn't have to patch Hunter yet I tried to comment out the setting of `HUNTER_ROOT` in the above, but that leads to the following error:

```
CMake Error at /usr/share/cmake-3.16/Modules/ExternalProject.cmake:2530 (message):
  URL_HASH is set to

    SHA1=xxxxxxxxxx

  but must be ALGO=value where ALGO is

    MD5|SHA1|SHA224|SHA256|SHA384|SHA512|SHA3_224|SHA3_256|SHA3_384|SHA3_512

  and value is a hex string.
```

**Comment by CarloWood** [comment] 2019-12-31 10:13
Ok, that fixed itself after removing `_Base`. This is the second time that I ran into a fatal error that could only be fixed by deleting all of `_Base`...

**Closed** 2020-01-03 14:13 UTC

**Comment by drywolf** [comment] 2020-01-09 22:13
@CarloWood Sorry I didn't check my github over the holidays, great that you could figure out the problem. 👍

**Comment by madmongo1** [comment] 2020-04-22 10:46
I've just had this error when using the latest hunter release.

Is there an easy-to-understand fix or workaround? I'm not an expert in hunter's internals.

```
include(cmake/HunterGate.cmake)
HunterGate(
        URL "https://github.com/cpp-pm/hunter/archive/v0.23.253.tar.gz"
        SHA1 "88ea6d37c897a81a080eb9ae0f69d7807bbb3c73"
)
```
